name: Staging Build

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  staging-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      # Setup Expo
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          expo-cache: true
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build APK for staging
      - name: Build APK
        run: eas build --profile preview --platform android  --non-interactive